### ISSUE TITLE
Left part of the text cut off in the end with the middle truncate

### ISSUE THREAD

**Issue by abaikov** [loktar00/react-text-overflow#4]
It's a screenshot from the demo https://loktar00.github.io/react-text-overflow/

<img width="979" alt="image" src="https://github.com/user-attachments/assets/99790f3e-19cb-48a5-9577-6f0095e018f8">

The letter "e" in the "Change the size" is shown only in half

**Comment by loktar00** [comment]
That's by design honestly, could look at it "popping" each one.
